### Set general CMake configuration and define helper variables and functions

# We only cache the variables we want the user to be able to override
set (CMAKE_EXPORT_COMPILE_COMMANDS ON)
set (CMAKE_CXX_STANDARD 17)
set (CMAKE_CXX_STANDARD_REQUIRED ON)
set (CMAKE_CXX_EXTENSIONS OFF)
set (CMAKE_CXX_VISIBILITY_PRESET hidden)
set (CMAKE_INTERPROCEDURAL_OPTIMIZATION_OPTIMIZED ON CACHE BOOL "Toggle LTO for optimized builds")
set (CMAKE_DEBUG_POSTFIX d)
set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)

list (APPEND OWN_INCLUDE_DIRS
    "$<BUILD_INTERFACE:$<TARGET_PROPERTY:SOURCE_DIR>/include>"
    "$<INSTALL_INTERFACE:$<INSTALL_PREFIX>/include>"
    "$<BUILD_INTERFACE:$<TARGET_PROPERTY:BINARY_DIR>/include>"
)

if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/install" CACHE PATH "Installation prefix" FORCE)
endif()
include(GNUInstallDirs)
